2anki/web

- package-lock.json
- src/components/forms/LoginForm.tsx
- src/lib/Backend.ts
This is preparation for using Netlify for all the frontend requests.
> fix: use /api for all server requests

- src/lib/Backend.ts
Closes: https://github.com/2anki/web/issues/30
> fix: clear cookies on logout

- src/components/text/BlueHeading3.tsx
This should resolve width issues on mobile.
> fix: removed fixed size on heading

- src/lib/interfaces/NotionObject.ts
- src/pages/Search/helpers/useNotionData.tsx
Related-to: https://github.com/2anki/server/issues/554
> style: remove any usage

- src/App.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/pages/MyUploads/hooks/usePatreon.tsx
- src/pages/Search/index.tsx
- src/pages/Upload/components/UploadForm.test.tsx
- src/pages/Upload/components/UploadForm.tsx
- src/pages/Upload/helpers/isAboveFreeTier.test.ts
- src/pages/Upload/helpers/isAboveFreeTier.ts
- src/pages/Upload/index.tsx
This needs some server changes to work properly.
> feat: allow patrons to upload past the 100MB limit

- src/components/modals/SettingsModal.tsx
This will ensure the user written changes get higher precedence.
> feat: add template for custom style

- src/lib/Backend.ts
- src/lib/handleRedirect.ts
- src/pages/MyUploads/components/ImposedLimits.tsx
- src/pages/MyUploads/components/UploadObjectEntry.tsx
- src/pages/MyUploads/components/styled.tsx
- src/pages/MyUploads/index.tsx
> feat: improvements to the my uploads page

- src/pages/Home/components/Sections/about/index.tsx
- src/pages/Home/components/Sections/benefits/benefits.ts
- src/pages/Home/components/Sections/hero/index.tsx
Also add missing class for hero section.
> chore: update text on home

- src/App.tsx
It's more user friendly since we can have links too.
> feat: render html from server

- src/pages/Search/components/DefineRules.tsx
- src/pages/Search/components/SearchObjectEntry/index.tsx
- src/pages/Search/components/WorkspaceHeader.tsx
Closes: https://github.com/2anki/server/issues/600
> fix(hotjar): do not record user workspace title / search results

- src/pages/MyUploads/index.tsx
> chore: supress finished jobs upload

- package-lock.json
- package.json
- src/components/modals/SettingsModal.tsx
- src/lib/Backend.ts
- src/pages/Search/helpers/useNotionData.tsx
- src/pages/Templates/index.tsx
Server changes have to be merged first https://github.com/2anki/server/pull/735
> feat: store templates wip

- src/components/BecomeAPatron.tsx
Using this so automatic translation tools will translate the text.
> feat: make the patreon button text

- src/pages/MyUploads/hooks/useUploads.tsx
Closes: https://github.com/2anki/web/issues/134
> fix: send delete key when batch deleting uploads

- package-lock.json
- package.json
> Revert "chore(deps): bump @fremtind/jkl-accordion-react from 7.0.10 to 8.0.2"

- src/App.tsx
- src/index.tsx
- src/lib/hooks/useQuery.ts
- src/pages/Learn/index.tsx
- src/pages/Search/index.tsx
Caused by recent dependabot merges.
> fix: dependency issues

- package-lock.json
- src/index.tsx
- src/pages/Learn/index.tsx
> fix: load next index faster

- src/pages/Learn/components/SelectionButton.tsx
- src/pages/Learn/index.tsx
> feat: use colour indicator for extract button

- src/App.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/components/NavigationBar/helpers/isLoginPage.ts
- src/components/forms/LoginForm.tsx
- src/components/forms/RegisterForm.tsx
- src/lib/handleRedirect.ts
Also removing verification page in preperation of https://github.com/2anki/server/pull/875
> fix: do not show navbar in login page

- src/lib/backend/index.ts
> fix(backend): send correct settings payload

- src/components/NavigationBar/helpers/getNavbarEnd.tsx
Otherwise mobile users have no way to delete their accounts.
> feat: show the delete account button on mobile

- src/pages/MyUploads/components/ListJobs/StatusTag.tsx
- src/pages/Search/components/SearchObjectEntry/index.tsx
Also ensure messages are displayed on error path.
> fix: add new status for uploads

- src/pages/Home/components/Sections/about/index.tsx
- src/pages/Home/components/Sections/hero/index.tsx
getting-started page is being deprecated
> feat: use upload link getting started CTA

- src/store/supportedOptions.ts
> feat: remove the notion link card option

- src/components/forms/LoginForm/index.tsx
- src/components/forms/LoginForm/styled.tsx
Previously hard to see when tabbing through on a chromebook.
> fix: change the hover color on the login submit

- package-lock.json
- package.json
- src/pages/Search/components/DefineRules.tsx
- src/pages/Search/components/RuleDefinition.tsx
- src/pages/Search/components/styled.tsx
They are making annoying breaking changes. Don't have time to update.
> refactor: remove @fremtind/jkl-accordion-react

- src/pages/Upload/index.tsx
> fix: remove extra upload prefix

- CONTRIBUTING.md
- src/components/Footer.tsx
- src/components/Layout/SideBar/Meny.tsx
> chore(docs): remove Discord link

- src/components/Layout/SideBar/Meny.tsx
- src/components/NavigationBar/helpers/getNavbarStartRegularUser.tsx
> fix: use correct link for user uploads

- package-lock.json
- package.json
- src/components/Loading/index.tsx
> refactor: remove usehooks-ts dependency

- package-lock.json
- package.json
- src/App.tsx
- src/components/errors/ErrorPresenter.tsx
- src/components/errors/helpers/useDismissed.ts
Reducing the amount of updates.
> refactor: remove @fremtind/jkl-alert-message

- src/pages/MyUploads/index.tsx
The server is now redirecting to this page more frequently.
> feat: let user know in uploads page about limits

- src/pages/Search/components/DefineRules.tsx
Practical when using it with code blocks.
> feat: add quote as supported flashcard

- src/components/NavigationBar/NavigationBar.tsx
- src/pages/LoginPage/LoginPage.tsx
> fix: update join now links to /register path

- package-lock.json
- package.json
Fixes exceptions in the search page.
> fix: Update get-notion-object-title to version 0.2.0

- src/pages/UploadPage/components/UploadForm.tsx
- src/pages/UploadPage/helpers/getAcceptedContentTypes.ts
Ref: https://github.com/2anki/2anki.net/pull/1296
> fix: add CSV to the accepted content types

- src/components/Layout/PageLayout.tsx
Closes: https://github.com/2anki/2anki.net/issues/1336
> fix: show meny on the search side bar

- src/pages/SimplePage/helpers/getAcceptedContentTypes.ts
> feat: allow Markdown uploads

- package-lock.json
- package.json
- src/components/modals/SettingsModal/SettingsModal.tsx
- src/lib/text/app.document.json
- src/pages/UploadPage/UploadPage.tsx
Hoping this will reduce confusion.
> feat: show user info about file formats

- src/components/forms/RegisterForm.tsx
There are users creating passwords and forget them right after.
> feat: add a password confirmation box

- package-lock.json
- package.json
- src/App.tsx
- src/pages/SuccessfulCheckout/SuccessfulCheckout.tsx
Hoping to reduce support cases
> feat: add a succesful checkout page

- src/components/NavigationBar/NavigationBar.tsx
- src/lib/useIsLoggedIn.ts
- src/pages/PricingPage/PricingPage.tsx
Should reduce premature purchases that cause email linking issues.
> feat: show Stripe link only to logged in users

- src/components/icons/SettingsIcon.tsx
- src/pages/UploadPage/UploadPage.tsx
- src/pages/UploadPage/styled.tsx
> Revert "feat: remove card options"

- src/components/forms/WithGoogleLink.tsx
> Revert "chore: inform users about gmail issues"

- src/pages/HomePage/components/Sections/tier/TierSection.tsx
Also removed Patreon tier card.
> fix: show login url on front page subscribe link

- config/env.js
- public/index.html
- src/components/forms/WithGoogleLink.tsx
- src/pages/DownloadsPage/components/FinishedJobs.tsx
- src/pages/DownloadsPage/components/ListJobs/DeleteButton.tsx
- src/pages/DownloadsPage/components/UploadObjectEntry.tsx
- **build: use expand function**
- **refactor: remove font awesome**
> chore: cleaning up build issues

- src/lib/backend/getUserLocals.ts
- src/pages/DownloadsPage/DownloadsPage.tsx
- src/pages/SearchPage/components/DefineRules.tsx
- src/pages/SettingsPage/SettingsPage.tsx
handle logout and give info about cancelled jobs.
> fix: handle logout

- config/webpack.config.js
- config/webpackDevServer.config.js
- src/lib/text/app.document.json
- src/pages/DownloadsPage/DownloadsPage.tsx
- src/pages/DownloadsPage/components/FinishedJobs.tsx
- src/pages/DownloadsPage/components/ListJobs/StatusTag.tsx
- src/pages/DownloadsPage/components/ListJobs/index.tsx
- src/pages/DownloadsPage/components/UnfinishedJobsInfo.tsx
- **fix: get local dev working**
- **feat: improve the readability of the downloads page**
> feat: improve readability of the download page

- package-lock.json
- package.json
- src/App.tsx
- src/components/Layout/PageLayout.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/components/NavigationBar/helpers/useNavbarEnd.tsx
- src/lib/hooks/useUserLocals.ts
- src/lib/useIsLoggedIn.ts
- src/pages/HomePage/HomePage.tsx
- src/pages/HomePage/components/Sections/tier/TierSection.tsx
- src/pages/PricingPage/PricingPage.tsx
- src/pages/SettingsPage/SettingsPage.tsx
In production when switching between computers, the local token would
make you believe you were logged in and trigger requests that were
guaranteed to fail. Instead of assuming the local token is correct we
let the server verify it by giving check the user id we get back from
the user locals call.
> feat: resolve inconsistent login state

- .github/workflows/playwright.yml
- .gitignore
- package-lock.json
- package.json
- playwright.config.ts
- tests/home.spec.ts
> test: add Playwright

- src/pages/SearchPage/SearchPage.tsx
- src/pages/SearchPage/components/ConnectNotion.tsx
This page is generating a lot of unauthorized requests due to the way it
was rendering the search container. Now it will show a little bit more
info and stop these request.
This is just first pass and it will be improved in subsequent
iterations.
> feat: cleanup the connect to notion page

- package-lock.json
- package.json
- src/App.tsx
- src/lib/backend/api.ts
- src/lib/backend/http.ts
- src/pages/NotFoundPage.tsx
- tsconfig.json
- **fix: import issues**
- **fix: add missing handling of 401 / 404 get request**
- **feat: Add default 404 page**
> fix: handle outstanding bugs

- src/components/Footer.tsx
> fix: improve footer mobile responsiveness

- src/App.tsx
- src/components/NavigationBar/NavigationBar.tsx
- src/pages/SearchPage/SearchPage.tsx
- src/pages/SearchPage/helpers/useNotionData.tsx
> fix: remove annoying flicker of search

- src/pages/AccountPage/AccountPage.tsx
We don't want to expose these.
> fix: add missing masking on user account

- src/pages/SearchPage/components/SearchContainer.tsx
> feat: show loading inline

- package-lock.json
- package.json
- src/pages/KiPage/KiPage.tsx
- src/pages/KiPage/components/KiCard.tsx
- src/pages/KiPage/components/KiSessionMenu.tsx
- src/pages/KiPage/hooks/useKiFlashcards.ts
- src/pages/KiPage/hooks/useKiSession.ts
- src/pages/KiPage/types.ts
> feat: add empty state

- package-lock.json
- package.json
- src/pages/HomePage/HomePage.tsx
- src/pages/HomePage/components/HomePageAnonHeader.tsx
- src/pages/HomePage/components/HomePageLoggedInHeader.tsx
- src/pages/HomePage/components/VideosAndDocs.tsx
> feat: add docs section for new users

- src/pages/AccountPage/AccountPage.tsx
> fix: use test billing portal in development

- src/components/modals/SettingsModal/SettingsModal.tsx
> feat: card option for setting user instructions
